# -*- coding: utf-8 -*-
#
# HemoCell documentation build configuration file, created by
# sphinx-quickstart on Mon Nov 27 16:26:36 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os
import pathlib
import subprocess
import sys

rootpath = pathlib.Path(__file__).parents[2]

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.todo',
    'sphinx.ext.mathjax',
    'sphinx.ext.intersphinx',
    'sphinxcontrib.bibtex',
    'breathe',
    'myst_parser',       # Markdown (.md) support
    'sphinx_copybutton',  # copy buttons on code blocks
    'sphinx_design',      # cards, grids, tabs, ...
]

# point `sphinxcontrib.bibtex` to the right bib file
bibtex_bibfiles = ['refs.bib']

# -- MyST (Markdown) configuration ----------------------------------------
# Enable a useful subset of MyST extensions so Markdown pages can use the same
# rich features (admonitions, math, ...) as the reStructuredText pages.
myst_enable_extensions = [
    'colon_fence',
    'deflist',
    'dollarmath',
    'linkify',
    'substitution',
]
myst_heading_anchors = 3

# Only copy the actual code when clicking the copy button, stripping common
# shell/REPL prompts so pasted snippets run as-is.
copybutton_prompt_text = r">>> |\.\.\. |\$ |# |user@local.*?\$ |user@local.*?: "
copybutton_prompt_is_regexp = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames. Both reStructuredText and Markdown are
# supported (the latter via the MyST parser).
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}

# Ensure unique labels of sections by prefixing each section with the current
# file. This allows to have multiple documentation pages with the same section
# layout and still being able to uniquely refer to each individual section.
autosectionlabel_prefix_document = True

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'HemoCell'
copyright = u'2024, Computational Science Lab, University of Amsterdam'
author = u'HemoCell Developers'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = u'2.8'
# The full version, including alpha/beta/rc tags.
release = u'2.8'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.

# NOTE: exclude files in `./cases` that are already discovered automatically
# to suppress warnings that duplicate files are discovered.
exclude_patterns = ['_build']

# The reST default role (used for this markup: `text`) to use for all
# documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
#keep_warnings = False

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Link checking --------------------------------------------------------
# Some publisher sites (and a few DOI redirects) reject automated requests with
# a 403, even though the links are valid in a browser. Ignore those so that
# `make linkcheck` reports only genuinely broken links.
linkcheck_ignore = [
    r'https?://(www\.)?sciencedirect\.com/.*',
    r'https?://(www\.)?mdpi\.com/.*',
    r'https?://doi\.org/10\.3390/.*',  # MDPI DOIs
]
# Treat slow/occasionally-flaky links gracefully.
linkcheck_timeout = 15
linkcheck_retries = 2

breathe_projects = {"hemocell": "../doxygen/xml/"}
breathe_default_project = "hemocell"
breathe_default_members = ('members', 'undoc-members')

# Run Doxygen manually to (re)generate the Doxygen pages that are included
# within the Sphinx-documentation pages. If the command failed, e.g. when
# Doxygen is not installed on the system, we can still continue. However, the
# links to any Doxygen-generated pages will return in "file not found"
# errors on the local pages.
try:
    subprocess.run(['doxygen', 'config.xml'],
                   cwd=rootpath.joinpath('doc/doxygen'))
except Exception as error:
    print("\nFailed to generate Doxygen pages with error: {}\n".format(error))

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages. HemoCell uses the
# Sphinx Book Theme (https://sphinx-book-theme.readthedocs.io).
html_theme = 'sphinx_book_theme'

# Theme options customise the look and feel. See the Sphinx Book Theme docs
# for the full list of available options.
html_theme_options = {
    "repository_url": "https://github.com/UvaCsl/HemoCell",
    "repository_branch": "master",
    "path_to_docs": "doc/user_guide",
    "use_repository_button": True,
    "use_issues_button": True,
    "use_edit_page_button": True,
    "use_download_button": True,
    "home_page_in_toc": True,
    "show_navbar_depth": 1,
    "show_toc_level": 2,
    "logo": {
        "text": "HemoCell",
    },
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/UvaCsl/HemoCell",
            "icon": "fa-brands fa-github",
        },
        {
            "name": "Website",
            "url": "https://hemocell.eu",
            "icon": "fa-solid fa-globe",
        },
    ],
}

# A shorter, explicit title used in the browser tab and navigation bar.
html_title = "HemoCell Documentation"

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = "_static/logo.png"

# The name of an image file (relative to this directory) to use as a favicon of
# the docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr'
#html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# Now only 'ja' uses this config value
#html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
#html_search_scorer = 'scorer.js'

# Output file base name for HTML help builder.
htmlhelp_basename = 'HemoCelldoc'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
#'papersize': 'letterpaper',

# The font size ('10pt', '11pt' or '12pt').
#'pointsize': '10pt',

# Additional stuff for the LaTeX preamble.
#'preamble': '',

# Latex figure (float) alignment
#'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'HemoCell.tex', u'HemoCell Documentation',
     u'HemoCell Developers', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'hemocell', u'HemoCell Documentation',
     [author], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'HemoCell', u'HemoCell Documentation',
     author, 'HemoCell', 'One line description of project.',
     'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#texinfo_no_detailmenu = False
