name: HemoCell_CI

on:
# there is no way trigger the workflow when a pull request is merged.
# however, since a merged pull always results in a push, we use the push event here.
  push:
    branches: 
      - master
      - develop
      
# enable github workflow to run whenever a PR is created on any branch
# that will be afterwards merged on develop 
  pull_request:
    types: [opened, reopened, review_requested]

jobs:

  hemocell_ci_workflow:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Install hemocell dependencies and create artifacts
      run: |
        sudo apt-get update --yes -qq
        sudo apt-get install --yes -qq git g++ cmake make libopenmpi-dev libhdf5-mpi-dev \
                             libhdf5-dev patch wget ccache
        ./setup.sh > /dev/null
        mkdir -p build && cd build
        cmake .. 
      
    - name : build hemocell and examples
      run : |
        while read target; do
          cmake --build . --target ${target}
        done < <(cut -d '"' -f2 < ../examples/CMakeLists.txt)
      working-directory: build
    
    - name : build and run validation tests
      run : |
        cmake --build . --target hemocell_test
        export GTEST_FILTER="Validation*"
        cd ..
        mpirun -n 4 hemocell_test
      working-directory: build

    - name : build and run performance tests
      run : |
        export GTEST_FILTER="Performance*"
        mpirun -n 1 hemocell_test tests/performance/configs/config-1.xml
        mpirun -n 2 hemocell_test tests/performance/configs/config-2.xml
        mpirun -n 6 hemocell_test tests/performance/configs/config-6.xml
      working-directory: HemoCell-dev


    - name : build documentation
      run : |
        sudo apt-get -y update
        sudo apt-get install -y make doxygen graphviz fonts-freefont-ttf
        pip install -r requirements.txt
        cd user_guide
        make clean
        make html
      working-directory: doc
      
  
